export {getAllFriends, GET_FRIENDS_START, GET_FRIENDS_SUCCESS, GET_FRIENDS_FAILURE} from './GetFriends';
export {postLogin, POST_LOGIN_START, POST_LOGIN_SUCCESS, POST_LOGIN_FAILURE} from './PostLogin';
export {postFriend,POST_FRIEND_START,POST_FRIEND_SUCCESS,POST_FRIEND_FAILURE} from './PostFriend'